### ISSUE TITLE
Accessing animes with "/" (slash) in the title crashes the app

### ISSUE THREAD

**Issue by TrueSyan** [Chesire/Nekome#1162]
Crashdump:
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.240105.002/2024010400:user/release-keys
package: com.chesire.nekome:24010710
process: com.chesire.nekome
processUptime: 57361 + 205 ms
installer: com.android.packageinstaller

java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/item/98512374/Fate/stay night } cannot be found in the navigation graph d(0x0) startDestination={f(0xa1cd5107) route=anime}
	at androidx.navigation.d.k(SourceFile:120)
	at com.chesire.nekome.ui.RoutesKt$addSeriesRoutes$1$1.a0(SourceFile:40)
	at com.chesire.nekome.app.series.collection.ui.CollectionScreenKt$CollectionScreen$1$1.i(SourceFile:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.p(SourceFile:1)
	at ta.f0.run(SourceFile:1)
	at androidx.compose.ui.platform.o0.m0(SourceFile:7)
	at androidx.compose.ui.platform.n0.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.r1@59ff8cf, androidx.compose.runtime.b@206325c, l1{Cancelling}@f23a965, o0@8ea163a]

```

**Comment by TrueSyan** [comment]
I'll look into this later today if no one else does, but pretty sure it just needs some sanitization.
