### ISSUE TITLE
Latest Version not available on F-Droid.

### ISSUE THREAD

**Issue by liberec0** [Chesire/Nekome#985]
The latest versions of Nekome : v2.0.0 and v2.0.1 are not available on the fdroid repo. 
Checking the F-Droid Build Status, it can be seen that the build process for nekome fails. Attaching the log here:-
```
Traceback (most recent call last):
  File "/home/fdroid/fdroidserver/fdroidserver/build.py", line 1042, in main
    if trybuild(app, build, build_dir, output_dir, log_dir,
  File "/home/fdroid/fdroidserver/fdroidserver/build.py", line 813, in trybuild
    build_server(app, build, vcs, build_dir, output_dir, log_dir, force)
  File "/home/fdroid/fdroidserver/fdroidserver/build.py", line 272, in build_server
    raise BuildException(message.format(app.id, build.versionName),
fdroidserver.exception.BuildException: Build.py failed on server for com.chesire.nekome:2.0.0
==== detail begin ====
== Installed Android Tools ==

2023-05-02 06:36:36,490 DEBUG: Reading 'config.yml'
2023-05-02 06:36:36,507 DEBUG: ipfs_cid not found, skipping CIDv1 generation
2023-05-02 06:36:36,508 INFO: Creating log directory
2023-05-02 06:36:36,508 INFO: Creating temporary directory
2023-05-02 06:36:36,508 INFO: Creating output directory
2023-05-02 06:36:36,519 DEBUG: Getting git vcs interface for https://github.com/Chesire/Nekome.git
2023-05-02 06:36:36,520 DEBUG: Checking com.chesire.nekome:23042320
2023-05-02 06:36:36,520 INFO: Building version 2.0.0 (23042320) of com.chesire.nekome
2023-05-02 06:36:36,520 DEBUG: > sudo passwd --lock root
passwd: password expiry information changed.
2023-05-02 06:36:37,232 DEBUG: > sudo SUDO_FORCE_REMOVE=yes dpkg --purge sudo
(Reading database ... 36747 files and directories currently installed.)
Removing sudo (1.9.5p2-3+deb11u1) ...
Purging configuration files for sudo (1.9.5p2-3+deb11u1) ...
dpkg: warning: while removing sudo, directory '/etc/sudoers.d' not empty so not removed
2023-05-02 06:36:48,035 INFO: Getting source for revision 4990da73baedf1a81fe79ec19e4deefdaae30601
2023-05-02 06:36:48,036 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:48,036 DEBUG: > git rev-parse --show-toplevel
2023-05-02 06:36:48,254 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:48,255 DEBUG: > git submodule foreach --recursive git reset --hard
2023-05-02 06:36:48,468 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:48,469 DEBUG: > git reset --hard
2023-05-02 06:36:48,912 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:48,913 DEBUG: > git submodule foreach --recursive git clean -dffx
2023-05-02 06:36:49,022 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:49,022 DEBUG: > git clean -dffx
2023-05-02 06:36:49,133 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:49,134 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com -c url.https://u:p@codeberg.org/.insteadOf=git@codeberg.org: -c url.https://u:p@codeberg.org.insteadOf=git://codeberg.org -c url.https://u:p@codeberg.org.insteadOf=https://codeberg.org fetch origin
2023-05-02 06:36:50,049 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:50,050 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com -c url.https://u:p@codeberg.org/.insteadOf=git@codeberg.org: -c url.https://u:p@codeberg.org.insteadOf=git://codeberg.org -c url.https://u:p@codeberg.org.insteadOf=https://codeberg.org remote prune origin
2023-05-02 06:36:50,563 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:50,564 DEBUG: > git -c core.askpass=/bin/true -c core.sshCommand=/bin/false -c url.https://.insteadOf=ssh:// -c url.https://u:p@bitbucket.org/.insteadOf=git@bitbucket.org: -c url.https://u:p@bitbucket.org.insteadOf=git://bitbucket.org -c url.https://u:p@bitbucket.org.insteadOf=https://bitbucket.org -c url.https://u:p@github.com/.insteadOf=git@github.com: -c url.https://u:p@github.com.insteadOf=git://github.com -c url.https://u:p@github.com.insteadOf=https://github.com -c url.https://u:p@gitlab.com/.insteadOf=git@gitlab.com: -c url.https://u:p@gitlab.com.insteadOf=git://gitlab.com -c url.https://u:p@gitlab.com.insteadOf=https://gitlab.com -c url.https://u:p@codeberg.org/.insteadOf=git@codeberg.org: -c url.https://u:p@codeberg.org.insteadOf=git://codeberg.org -c url.https://u:p@codeberg.org.insteadOf=https://codeberg.org fetch --prune --tags --force origin
2023-05-02 06:36:51,076 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:51,076 DEBUG: > git remote set-head origin --auto
2023-05-02 06:36:51,789 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:51,790 DEBUG: > git checkout -f 4990da73baedf1a81fe79ec19e4deefdaae30601
2023-05-02 06:36:52,201 DEBUG: Directory: build/com.chesire.nekome
2023-05-02 06:36:52,202 DEBUG: > git clean -dffx
2023-05-02 06:36:52,312 INFO: Creating local.properties file at build/com.chesire.nekome/local.properties
2023-05-02 06:36:52,314 INFO: Creating local.properties file at build/com.chesire.nekome/app/local.properties
2023-05-02 06:36:52,314 DEBUG: Removing debuggable flags from build/com.chesire.nekome/app
2023-05-02 06:36:52,394 INFO: Cleaning Gradle project...
2023-05-02 06:36:52,395 DEBUG: Directory: build/com.chesire.nekome/app
2023-05-02 06:36:52,395 DEBUG: > /home/vagrant/fdroidserver/gradlew-fdroid clean
Found 8.1.1 via distributionUrl
No hash for gradle version 8.1.1! Exiting...
2023-05-02 06:36:52,606 ERROR: Could not build app com.chesire.nekome: Error cleaning com.chesire.nekome:2.0.0
==== detail begin ====
Found 8.1.1 via distributionUrl
No hash for gradle version 8.1.1! Exiting...
==== detail end ====
2023-05-02 06:36:52,607 DEBUG: Error encoutered, stopping by user request.
==== detail end ====
```
The main error shows: 
```
Error cleaning com.chesire.nekome:2.0.0
```
I'm not familiar with kotlin nor the build process associated with it. Someone please take a look at it. I'd love for the latest version of nekome to be on f-droid !

**Comment by Chesire** [comment]
Looks like from their logs they are having an issue with their gradle cache, seems to happen whenever there is a gradle update. Once that's resolved it should automatically update when they do another scan. Will keep this open till I see its updated

**Comment by Chesire** [comment]
Looks like version 2.0.1 is now available on froid, will close this issue.
